M48
; DRILL file {KiCad (6.0.8)} date Fri Oct 21 18:27:40 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-21T18:27:40+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
%
G90
G05
T1
X112.42Y-33.02
X117.42Y-28.02
X117.42Y-38.02
X119.92Y-28.02
X119.92Y-38.02
T0
M30
